### ISSUE TITLE
Delphi 10.3 rio

### ISSUE THREAD

**Issue by caonUlisses** [ms301/FGX-FireMonkey#11]
Does the application support Delphi 10.3 Rio? We are using the components on a Delphi 10.2 project and are trying to upgrade it without success.
We followed the same steps we did on the 10.2 installation.
Does it support the new Rio version and if it does, do we need to take any extra steps to install it?

**Comment by SimaWB** [comment]
Here it is:
https://github.com/ilgazdev/FGX

**Comment by rafaelmairesrangel1982** [comment]
Olá eu estou tentando instalar e no Delphi RIO 10.3
e recebo essa mensangem de erro:
Cannot load package 'fgx260.'  It contains unit 'FGX.LinkedLabel.Win', which is also contained in package 'fgx240'.
caon você conseguiu ?

**Comment by caonUlisses** [comment]
Yes, using https://github.com/ilgazdev/FGX
Didn't have any problems at the time.

**Comment by rafaelmairesrangel1982** [comment]
Sim toda vez que eu tento instalar no Rio 10.3 ele dá este erro 
Cannot load package 'fgx260.' It contains unit 'FGX.LinkedLabel.Win', which is also contained in package 'fgx240'.

Você tem um passo a passo para eu realizar a instalação ?

**Comment by caonUlisses** [comment]
I don't remember how we did it, it's been quite some time... but you should try opening an issue at the other repo relating your problem

**Comment by IvanilsonConsultor** [comment]
Mano tu já tem um pacote carregando Fgx tem que remover.. procure na lista de pacote bpl do Delphi menu Components Install Package procure por 'fgx240'. e remove. Ai Fecha delphi reabre e instala o novo

**Comment by cirtasoft** [comment]
> 
> 
> Here it is:
> https://github.com/ilgazdev/FGX

please for sydny 10.4?
